# A Docker Compose file that can be used to deploy Hide and Squeak in a production. Can be adjusted to suit the deployment's needs.
services:
  server:
    image: mmk21/hide-and-squeak-server:latest
    ports:
      - 3010:3010
    environment:
      - "DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE_NAME}"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    # We use imresamu's fork of the image because it has multiplatform support (for ARMv8)
    # Feel free to switch to postgis/postgis if you'd prefer
    image: imresamu/postgis:17-3.5
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
